apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-14T11:51:04Z"
  labels:
    app: advisor-category-svcs
  name: advisor-category-svcs
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: advisor-category-svcs
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: advisor-category-svcs
        tier: backend
    spec:
      containers:
      - image: niravparikh05/advisor-category-svcs:v0.2
        imagePullPolicy: IfNotPresent
        name: advisor-category-svcs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
# create a service for advisor-category-svcs application
apiVersion: v1
kind: Service
metadata:
  name: advisor-category-svcs
  labels:
    app: advisor-category-svcs
spec:
  selector: 
    app: advisor-category-svcs
    tier: backend
  ports:
  -  port: 8080
     nodePort: 30060
  type: NodePort
