apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: finman-discovery
    tier: db
spec:
  serviceName: mongo-svc
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: db_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: db_passwd
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: finman-discovery
    type: service
spec:
  type: NodePort
  selector:
    app: mongodb
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31017
