apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: finman-discovery
    tier: db
spec:
  selector:
    matchLabels:
      app: mongo-express
      tier: db
  template:
    metadata:
      labels:
        app: mongo-express
        tier: db
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-express-secrets
              key: db_user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secrets
              key: db_passwd
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  labels:
    app: finman-discovery
    type: service
spec:
  type: ClusterIP
  selector:
    app: mongo-express
    tier: db
  ports:
    - port: 8081
      targetPort: 8081
