apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: finman-mongo-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity: 
    storage: 100Mi
  hostPath:
    path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  selector:
    matchLabels:
      app: finman-mongo-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

