apiVersion: v1
data:
  db_passwd: {{ .Values.finman.database.password | b64enc }}
  db_user: {{ .Values.finman.database.username | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.finman.database.dashboard.name }}-secrets
  namespace: {{ .Values.finman.namespace.name }}
