apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.finman.database.name }}
  labels:
    app: {{ .Values.finman.database.name }}
    tier: db
  namespace: {{ .Values.finman.namespace.name }}
spec:
  serviceName: mongo-svc
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - name: {{ .Values.finman.database.name }}
        image: mongo
        ports:
        - containerPort: {{ .Values.finman.database.port }}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: db_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: db_passwd
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.finman.database.name }}-svc
  labels:
    app: finman-discovery
    type: service
  namespace: {{ .Values.finman.namespace.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.finman.database.name }}
    tier: db
  ports:
    - port: {{ .Values.finman.database.port }}
      targetPort: {{ .Values.finman.database.port }}
      nodePort: 31017
