apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: finman-mongo-pv
  namespace: {{ .Values.finman.namespace.name }}
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  capacity: 
    storage: 100Mi
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Values.finman.namespace.name }}
spec:
  selector:
    matchLabels:
      app: finman-mongo-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi